version: '3.8'

services:
  # The FastAPI application service
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  # The Redis service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
